apiVersion: v1
kind: Service
metadata:
  name: patient-service
spec:
  selector:
    app: patient-app
  ports:
    - protocol: 'TCP'
      port: 9000
      targetPort: 9000
  type: LoadBalancer
