server:
  port: 7777
spring:
  application:
    name: API-GATEWAY
  boot:
    admin:
      client:
        url: http://localhost:8888
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
  main:
    web-application-type: reactive

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
