server:
  port: 8000
  servlet:
    context-path: /doctor
spring:
  application:
    name: DOCTOR-SERVICE
  boot:
    admin:
      client:
        url: http://localhost:8888
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    show-details: always